require 'rspec'
require 'bundler/setup'
require_relative '../models/automobile'
require_relative '../models/vehicle'
require_relative '../models/motorcycle'
require_relative '../lib/vehicle_collector'
